ansible setup with checking

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -21,10 +21,15 @@ jobs:
 
       - name: Setup Ansible
         run: |
-          sudo apt-get update -y
-          sudo apt install software-properties-common -y
-          sudo apt-add-repository --yes --update ppa:ansible/ansible
-          sudo apt-get install -y ansible
+          if ! command -v ansible &> /dev/null; then
+            echo "Ansible not found, installing..."
+            sudo apt-get update -y
+            sudo apt install software-properties-common -y
+            sudo apt-add-repository --yes --update ppa:ansible/ansible
+            sudo apt-get install -y ansible
+          else
+            echo "Ansible is already installed"
+          fi
           ansible --version
 
       # - name: SSH into Master node and Run the deployent file
